###########################################################
# LOGGER SETTINGS #
###########################################################
log_dir: "spec/log"
txt_log: log.txt
html_log: log.html
rawler_log: rawler_log.txt
selenium_server_log: selenium-server.log
required_clean_logs: true
hide_datetime_from_log: true

driver: selenium

###########################################################
# MAIL SETTINGS                                           #
###########################################################

mail_smtp_server: smtp.demo.com
mail_smtp_port: 25
mail_smtp_domain: demo.com
mail_smtp_user_name: test_user
mail_smtp_user_pass: mypass

mail_pop3_server: pop.demo.com
mail_pop3_port: 995
mail_pop3_timeout: 120
mail_pop3_domain: ${mail_smtp_domain}
mail_pop3_user_name: test_user
mail_pop3_user_pass: mypass

